id: I8B1FB7BB
imported: 2023-01-05 12:21:44.425790
last_modified: 2023-01-05 12:21:44.425815
bases:
  I1PD95846:
    base_file: I1PD95846.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95852:
    base_file: I1PD95852.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95853:
    base_file: I1PD95853.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95859:
    base_file: I1PD95859.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95863:
    base_file: I1PD95863.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95869:
    base_file: I1PD95869.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95870:
    base_file: I1PD95870.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95871:
    base_file: I1PD95871.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95872:
    base_file: I1PD95872.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95877:
    base_file: I1PD95877.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95878:
    base_file: I1PD95878.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95879:
    base_file: I1PD95879.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95882:
    base_file: I1PD95882.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95883:
    base_file: I1PD95883.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95884:
    base_file: I1PD95884.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95885:
    base_file: I1PD95885.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95886:
    base_file: I1PD95886.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95887:
    base_file: I1PD95887.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95888:
    base_file: I1PD95888.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95889:
    base_file: I1PD95889.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95891:
    base_file: I1PD95891.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95892:
    base_file: I1PD95892.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95902:
    base_file: I1PD95902.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95942:
    base_file: I1PD95942.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95954:
    base_file: I1PD95954.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95959:
    base_file: I1PD95959.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95960:
    base_file: I1PD95960.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95961:
    base_file: I1PD95961.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
  I1PD95965:
    base_file: I1PD95965.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9755740258134236
copyright:
  status: Unknown
  notice: ''
